disableKinds = ['rss', 'taxonomy', 'term']
enableGitInfo = true
enableRobotsTXT = true

[frontmatter]
publishDate = [':git', 'publishdate', 'date']
lastmod = [':git', 'lastmod', 'publishdate', 'date']

[caches]
[caches.images]
dir = ':cacheDir/images'

[services]
[services.rss]
limit = 25
