disableKinds = ['rss', 'taxonomy', 'term']
enableGitInfo = true
enableRobotsTXT = true

[frontmatter]
publishDate = [':git', 'publishdate', 'date']
lastmod = ['lastmod', ':git', 'publishdate', 'date']

[caches.images]
dir = ':cacheDir/images'

[services.rss]
limit = 25

[markup.goldmark.renderer]
unsafe = true
