---
name: Hugo Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.164.0
      HUGO_CACHEDIR: /tmp/hugo_cache
      TZ: Asia/Jakarta
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - uses: actions/cache@v6
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build static pages
        run: hugo build --gc

      - uses: peaceiris/actions-gh-pages@v4
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
